About this file

Suggest Edits
The Heart Disease Prediction Dataset is a synthetic medical dataset created for machine learning, data analysis, and predictive modeling tasks. The dataset contains 1000 patient records with multiple health-related features including glucose level, cholesterol level, blood pressure, BMI, heart rate, lifestyle habits, and family medical history.

The primary objective of this dataset is to predict the likelihood of heart disease risk using various clinical and lifestyle indicators. The target column (disease) is designed for binary classification tasks and contains two classes: Yes and No.

In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix

In [24]:
df=pd.read_csv("disease_prediction.csv")
df.head()

,patient_id,age,gender,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate,smoking,alcohol_consumption,physical_activity,family_history,disease
0,1,32,Male,101,235,152,79,28.5,73,No,Yes,Low,Yes,Yes
1,2,31,Male,124,191,134,77,33.9,71,No,Yes,Low,Yes,Yes
2,3,45,Male,57,141,114,71,27.2,79,Yes,Yes,Low,No,No
3,4,75,Female,69,268,120,82,21.5,61,Yes,Yes,Medium,No,Yes
4,5,53,Male,107,163,131,75,23.3,73,Yes,No,Low,Yes,Yes

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   patient_id           1000 non-null   int64
 1   age                  1000 non-null   int64
 2   gender               1000 non-null   object
 3   glucose_mg_dl        1000 non-null   int64
 4   cholesterol_mg_dl    1000 non-null   int64
 5   systolic_bp          1000 non-null   int64
 6   diastolic_bp         1000 non-null   int64
 7   bmi                  1000 non-null   float64
 8   heart_rate           1000 non-null   int64
 9   smoking              1000 non-null   object
 10  alcohol_consumption  1000 non-null   object
 11  physical_activity    1000 non-null   object
 12  family_history       1000 non-null   object
 13  disease              1000 non-null   object
dtypes: float64(1), int64(7), object(6)
memory usage: 109.5+ KB

In [26]:
df.shape

(1000, 14)

In [27]:
df.columns

Index(['patient_id', 'age', 'gender', 'glucose_mg_dl', 'cholesterol_mg_dl',
       'systolic_bp', 'diastolic_bp', 'bmi', 'heart_rate', 'smoking',
       'alcohol_consumption', 'physical_activity', 'family_history',
       'disease'],
      dtype='object')

In [28]:
df.isnull().sum()

patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64

In [29]:
df.duplicated().sum()

np.int64(0)

In [30]:
for column in df.columns:    
    print(f"{column} Nan value counts:",df[df[column].isna()].count())
    print("\n")

patient_id Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


age Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


gender Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


glucose_mg_dl Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


cholesterol_mg_dl Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


systolic_bp Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


diastolic_bp Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


bmi Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


heart_rate Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


smoking Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


alcohol_consumption Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


physical_activity Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


family_history Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64


disease Nan value counts: patient_id             0
age                    0
gender                 0
glucose_mg_dl          0
cholesterol_mg_dl      0
systolic_bp            0
diastolic_bp           0
bmi                    0
heart_rate             0
smoking                0
alcohol_consumption    0
physical_activity      0
family_history         0
disease                0
dtype: int64

In [31]:
df.describe()

,patient_id,age,glucose_mg_dl,cholesterol_mg_dl,systolic_bp,diastolic_bp,bmi,heart_rate
count,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,500.500000,51.190000,104.163000,210.014000,123.893000,81.032000,26.093000,75.968000
std,288.819436,19.847514,25.076508,39.749111,18.701211,9.969974,4.758282,9.902982
min,1.000000,18.000000,30.000000,89.000000,67.000000,49.000000,16.000000,47.000000
25%,250.750000,33.000000,87.000000,183.000000,111.000000,74.000000,22.900000,70.000000
50%,500.500000,52.500000,105.000000,210.500000,124.000000,81.000000,26.000000,76.000000
75%,750.250000,69.000000,121.000000,235.250000,135.000000,88.000000,29.300000,83.000000
max,1000.000000,85.000000,184.000000,339.000000,195.000000,113.000000,41.500000,114.000000

In [32]:
df.physical_activity.value_counts()

physical_activity
Medium    344
High      344
Low       312
Name: count, dtype: int64

In [33]:
#convering the categorical data into numerical data

#Column with binary categorical data can be converted into numerical data using map function
df["gender"]=df["gender"].map({"Male":1,"Female":0})
df["smoking"]=df["smoking"].map({"Yes":1,"No":0})
df["alcohol_consumption"]=df["alcohol_consumption"].map({"Yes":1,"No":0})
df["family_history"]=df["family_history"].map({"Yes":1,"No":0})

#Columns with more than two categories can be converted into numerical data using get_dummies function
df=pd.get_dummies(df,columns=["physical_activity"],drop_first=True)

In [34]:
#dividing the data into features and target
X=df.drop("disease",axis=1)
y=df["disease"]   
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

In [39]:
logistic=LogisticRegression(max_iter=10000)
logistic.fit(X_train,y_train)
y_pred=logistic.predict(X_test)

print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

          No       0.83      0.88      0.86       153
         Yes       0.87      0.82      0.84       147

    accuracy                           0.85       300
   macro avg       0.85      0.85      0.85       300
weighted avg       0.85      0.85      0.85       300

In [41]:

print(confusion_matrix(y_test,y_pred))

[[135  18]
 [ 27 120]]