# Label/Ordinal Encoding

In [3]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder

In [5]:
df=pd.read_csv('/content/drive/MyDrive/Feature Engineering and ETA/HousePrice_AdvRegressionTechnique/train.csv')
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [6]:
df["LotShape"].value_counts()

LotShape
Reg    925
IR1    484
IR2     41
IR3     10
Name: count, dtype: int64

In [14]:
encoder=LabelEncoder()
encoder_val=encoder.fit_transform(df[["LotShape"]])

/usr/local/lib/python3.12/dist-packages/sklearn/preprocessing/_label.py:110: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [15]:
encoder_val

array([3, 3, 0, ..., 3, 3, 3])

# Ordinal Encoding

In [16]:
from sklearn.preprocessing import OrdinalEncoder

In [18]:
df_n=pd.DataFrame({'size':['small','medium','large','medium','small','large']})

In [19]:
encoder_1=OrdinalEncoder(categories=[['small','medium','large']])

In [20]:
encoder_1.fit_transform(df_n)

array([[0.],
       [1.],
       [2.],
       [1.],
       [0.],
       [2.]])

In [21]:
encoder_1.transform([['small']])

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(

array([[0.]])